import csv, os, pycountry, colorama, random

CSV_FOLDER = "./csv"
CSV_TARGET_FILE = "./csv/food.csv"
FOOD_ELEMENTS = [" cuisine", "Cuisine of"]
COUNTRY_ELEMENTS = [country.name for country in pycountry.countries]
BANNED_WORDS = [ # ChatGPT Generated this list
    # Root Concepts
    "Cuisine",
    "Culture",
    "Food",
    "Portal",
    "Index",
    "List",
    "Team",
    "Operation",
    "Outline",
    "History",
    "Comparison",
    "Diet",
    "Vegetarianism",
    "Islam",
    "Cuisine",
    "Culture",
    "Food",
    "List",
    "Portal",
    "Index",
    "Team",
    "Operation",
    "Outline",
    "History",
    "Comparison",
    "Diet",
    "Vegetarianism",
    "Islam",
    "Culture",
    "Food",
    "List",
    "Portal",
    "Index",
    "Team",
    "Operation",
    "Outline",
    "History",
    "Comparison",
    "Diet",
    "Vegetarianism",
    "Islam",
    "Robot",
    "Factory",

    # Places
    "Thulhaadhoo",
    "Padang Panjang",
    "West Tampa",
    "Bagansiapiapi",
    "Padang Matsirat",
    "Wichian Buri district",
    "Brickfields",
    "Seremban District",
    "Toft",
    "Wilstead",
    "Buchkirchen",
    "Dhërmi",
    "Shelley",
    "El Quisco",
    "Huancarqui District",
    "Majes District",
    "Bouza Department",
    "Dély Ibrahim",
    "Orahovac",
    "Nankin-machi",

    # People
    "Sanjeev Kapoor",
    "Cheong Liew",
    "Vikas Khanna",
    "John Torode",
    "Cindy McCain",
    "Anwar Choudhury",
    "Manju Malhi",
    "Abdul Latif",
    "Joan Nathan",
    "George Mardikian",
    "Nelson Mandela",
    "Maggie Beer",
    "Fabio Lanzoni",
    "Tony Brent",
    "David Galenson",
    "Aleix Espargaró",
    "Daren Ganga",
    "Toshikatsu Matsuoka",
    "Gotabaya Rajapaksa",
    "Mahabir Pun",
    "Yu Hayami",
    "Hallgerður Gísladóttir",
    "Jean-Paul Bruneteau",
    "Vic Cherikoff",

    # Companies / Brands / Restaurants
    "Wolf Blass",
    "Haigh's Chocolates",
    "Golden North",
    "Beerenberg Farm",
    "Sakae Sushi",
    "Long Beach Seafood Restaurant",
    "Jumbo Seafood",
    "Mitsuwa Marketplace",
    "Wendy's Milk Bar",
    "Bloom's restaurant",
    "Fogo de Chão",
    "Versailles",
    "Quay",
    "Domino's Pizza",
    "Adyar Ananda Bhavan",
    "Veeraswamy",
    "Cibo Espresso",
    "Kart's",
    "Yatir winery",
    "Recanati winery",
    "Elderton Wines",
    "Pewsey Vale",
    "Torbreck",
    "Seppeltsfield",
    "Mountadam Vineyards",
    "Barkan Wine Cellars",
    "Schiller Vineyards",
    "Yalumba",
    "Golden Krust",
    "Trend Drinks",
    "Woodroofe",
    "Farmers Union",
    "Bee Cheng Hiang",
    "Prigat",
    "Sizzler",
    "Koni Store",
    "Ching's Secret",
    "Aashirvaad",
    "Wikipedia",

    # Abstract Concepts
    "Americanization",
    "Arab Agricultural Revolution",
    "Assyrian culture",
    "Culinary tourism",
    "Food politics",
    "Food prohibitions",
    "Food waste",
    "Intensive animal farming",
    "Prophetic medicine",
    "Homelessness",

    # Media / Shows / Fiction
    "A Cook's Tour",
    "Anna & Kristina's Grocery Bag",
    "TV or Not TV",
    "Asadora",
    "The Secret of the Grain",
    "Upin & Ipin",
    "Chowder",
    "Tikka to Ride",
    "Sukiyaki Western Django",
    "Fantozzi",
    "Masala film",
    "Fan Pan Tae",
    "The Amazing Race 18",
    "Great British Railway Journeys",
    "The Rippling Blossom",

    # Miscellaneous
    "BP-5 Compact Food",
    "GARIOA",
    "Feldgendarmerie",
    "437th Airlift Wing",
    "Progress M-01M",
    "Satellite television",
    "UNESCO Intangible Cultural Heritage Lists",
    "Food contact materials",
    "Food contaminant",
    "Geographically Indicated Food",
    "Taste",
    "Serving size",
    "Guideline Daily Amount",
    "Platter",
    "Rolling pin",
    "Flattop grill",
    "Dish structure",
    "Food model",
    "Federal Ministry of Agriculture, Food and Regional Identity",
    "Etar Architectural-Ethnographic Complex",
    
    # === Root Concepts ===
    "Cuisine",
    "Food",
    "Dish",
    "Dishes",
    "Foods",

    # === Existing Root Concepts (deduplicated) ===
    "Culture",
    "Speak",
    "People",
    "School",
    "Diamond",
    "Airline",
    "Book",
    "Famine",
    "famine",
    "File",
    "virus",
    "fever",
    "Template",
    "How",
    "Portal",
    "Index",
    "List",
    "Team",
    "Operation",
    "Outline",
    "History",
    "Comparison",
    "Diet",
    "Vegetarianism",
    "Islam",

    # === Places ===
    "Thulhaadhoo",
    "Padang Panjang",
    "West Tampa",
    "Bagansiapiapi",
    "Padang Matsirat",
    "Wichian Buri district",
    "Brickfields",
    "Seremban District",
    "Toft",
    "Wilstead",
    "Buchkirchen",
    "Dhërmi",
    "Shelley",
    "El Quisco",
    "Huancarqui District",
    "Majes District",
    "Bouza Department",
    "Dély Ibrahim",
    "Orahovac",
    "Nankin-machi",

    # === People ===
    "Sanjeev Kapoor",
    "Cheong Liew",
    "Vikas Khanna",
    "John Torode",
    "Cindy McCain",
    "Anwar Choudhury",
    "Manju Malhi",
    "Abdul Latif",
    "Joan Nathan",
    "George Mardikian",
    "Nelson Mandela",
    "Maggie Beer",
    "Fabio Lanzoni",
    "Tony Brent",
    "David Galenson",
    "Aleix Espargaró",
    "Daren Ganga",
    "Toshikatsu Matsuoka",
    "Gotabaya Rajapaksa",
    "Mahabir Pun",
    "Yu Hayami",
    "Hallgerður Gísladóttir",
    "Jean-Paul Bruneteau",
    "Vic Cherikoff",

    # === Companies / Brands ===
    "Wolf Blass",
    "Haigh's Chocolates",
    "Golden North",
    "Beerenberg Farm",
    "Sakae Sushi",
    "Long Beach Seafood Restaurant",
    "Jumbo Seafood",
    "Mitsuwa Marketplace",
    "Wendy's Milk Bar",
    "Bloom's restaurant",
    "Fogo de Chão",
    "Versailles",
    "Quay",
    "Domino's Pizza",
    "Adyar Ananda Bhavan",
    "Veeraswamy",
    "Cibo Espresso",
    "Kart's",
    "Yatir winery",
    "Recanati winery",
    "Elderton Wines",
    "Pewsey Vale",
    "Torbreck",
    "Seppeltsfield",
    "Mountadam Vineyards",
    "Barkan Wine Cellars",
    "Schiller Vineyards",
    "Yalumba",
    "Golden Krust",
    "Trend Drinks",
    "Woodroofe",
    "Farmers Union",
    "Bee Cheng Hiang",
    "Prigat",
    "Sizzler",
    "Koni Store",
    "Ching's Secret",
    "Aashirvaad",

    # === Abstract Concepts ===
    "Americanization",
    "Arab Agricultural Revolution",
    "Assyrian culture",
    "Culinary tourism",
    "Food politics",
    "Food prohibitions",
    "Food waste",
    "Intensive animal farming",
    "Prophetic medicine",
    "Homelessness",

    # === Media / Shows ===
    "A Cook's Tour",
    "Anna & Kristina's Grocery Bag",
    "TV or Not TV",
    "Asadora",
    "The Secret of the Grain",
    "Upin & Ipin",
    "Chowder",
    "Tikka to Ride",
    "Sukiyaki Western Django",
    "Fantozzi",
    "Masala film",
    "Fan Pan Tae",
    "The Amazing Race 18",
    "Great British Railway Journeys",
    "The Rippling Blossom",

    # === Miscellaneous ===
    "BP-5 Compact Food",
    "GARIOA",
    "Feldgendarmerie",
    "437th Airlift Wing",
    "Progress M-01M",
    "Satellite television",
    "UNESCO Intangible Cultural Heritage Lists",
    "Food contact materials",
    "Food contaminant",
    "Geographically Indicated Food",
    "Taste",
    "Serving size",
    "Guideline Daily Amount",
    "Platter",
    "Rolling pin",
    "Flattop grill",
    "Dish structure",
    "Food model",
    "Federal Ministry of Agriculture, Food and Regional Identity",
    "Etar Architectural-Ethnographic Complex",
]


with open(file="./csv/links.csv", mode="r", encoding="utf-8") as mother_file, open(file=CSV_TARGET_FILE, mode="w", encoding="utf-8") as child_file:
    read_links = csv.reader(mother_file)
    write = csv.writer(child_file)

    for row in read_links:
        if any(item in row[1] for item in FOOD_ELEMENTS) and any(item in row[1] for item in COUNTRY_ELEMENTS) and not any(item in row[0] for item in FOOD_ELEMENTS) and not any(item in row[0] for item in COUNTRY_ELEMENTS) and not any(item in row[0] for item in BANNED_WORDS) and not any(item in row[1] for item in BANNED_WORDS):
            print(row)
            write.writerow(row)
print("Done!")