import csv, os, pycountry, colorama, random

CSV_FOLDER = "./csv"
CSV_TARGET_FILE = "./csv/food.csv"
FOOD_ELEMENTS = [" food", " dish", " cuisine", "Cuisine of", "Foods of", "Eating", "Lunch"]
COUNTRY_ELEMENTS = [country.name for country in pycountry.countries]
BANNED_WORDS = [ # ChatGPT Generated this list
    # Root Concepts
    "Cuisine",
    "Culture",
    "Food",
    "Portal",
    "Index",
    "List",
    "Team",
    "Operation",
    "Outline",
    "History",
    "Comparison",
    "Diet",
    "Vegetarianism",
    "Islam",
    "Cuisine",
    "Culture",
    "Food",
    "List",
    "Portal",
    "Index",
    "Team",
    "Operation",
    "Outline",
    "History",
    "Comparison",
    "Diet",
    "Vegetarianism",
    "Islam",
    "Cuisine",
    "Culture",
    "Food",
    "List",
    "Portal",
    "Index",
    "Team",
    "Operation",
    "Outline",
    "History",
    "Comparison",
    "Diet",
    "Vegetarianism",
    "Islam",
    "Robot",
    "Factory",

    # Places
    "Thulhaadhoo",
    "Padang Panjang",
    "West Tampa",
    "Bagansiapiapi",
    "Padang Matsirat",
    "Wichian Buri district",
    "Brickfields",
    "Seremban District",
    "Toft",
    "Wilstead",
    "Buchkirchen",
    "Dhërmi",
    "Shelley",
    "El Quisco",
    "Huancarqui District",
    "Majes District",
    "Bouza Department",
    "Dély Ibrahim",
    "Orahovac",
    "Nankin-machi",

    # People
    "Sanjeev Kapoor",
    "Cheong Liew",
    "Vikas Khanna",
    "John Torode",
    "Cindy McCain",
    "Anwar Choudhury",
    "Manju Malhi",
    "Abdul Latif",
    "Joan Nathan",
    "George Mardikian",
    "Nelson Mandela",
    "Maggie Beer",
    "Fabio Lanzoni",
    "Tony Brent",
    "David Galenson",
    "Aleix Espargaró",
    "Daren Ganga",
    "Toshikatsu Matsuoka",
    "Gotabaya Rajapaksa",
    "Mahabir Pun",
    "Yu Hayami",
    "Hallgerður Gísladóttir",
    "Jean-Paul Bruneteau",
    "Vic Cherikoff",

    # Companies / Brands / Restaurants
    "Wolf Blass",
    "Haigh's Chocolates",
    "Golden North",
    "Beerenberg Farm",
    "Sakae Sushi",
    "Long Beach Seafood Restaurant",
    "Jumbo Seafood",
    "Mitsuwa Marketplace",
    "Wendy's Milk Bar",
    "Bloom's restaurant",
    "Fogo de Chão",
    "Versailles",
    "Quay",
    "Domino's Pizza",
    "Adyar Ananda Bhavan",
    "Veeraswamy",
    "Cibo Espresso",
    "Kart's",
    "Yatir winery",
    "Recanati winery",
    "Elderton Wines",
    "Pewsey Vale",
    "Torbreck",
    "Seppeltsfield",
    "Mountadam Vineyards",
    "Barkan Wine Cellars",
    "Schiller Vineyards",
    "Yalumba",
    "Golden Krust",
    "Trend Drinks",
    "Woodroofe",
    "Farmers Union",
    "Bee Cheng Hiang",
    "Prigat",
    "Sizzler",
    "Koni Store",
    "Ching's Secret",
    "Aashirvaad",
    "Wikipedia",

    # Abstract Concepts
    "Americanization",
    "Arab Agricultural Revolution",
    "Assyrian culture",
    "Culinary tourism",
    "Food politics",
    "Food prohibitions",
    "Food waste",
    "Intensive animal farming",
    "Prophetic medicine",
    "Homelessness",

    # Media / Shows / Fiction
    "A Cook's Tour",
    "Anna & Kristina's Grocery Bag",
    "TV or Not TV",
    "Asadora",
    "The Secret of the Grain",
    "Upin & Ipin",
    "Chowder",
    "Tikka to Ride",
    "Sukiyaki Western Django",
    "Fantozzi",
    "Masala film",
    "Fan Pan Tae",
    "The Amazing Race 18",
    "Great British Railway Journeys",
    "The Rippling Blossom",

    # Miscellaneous
    "BP-5 Compact Food",
    "GARIOA",
    "Feldgendarmerie",
    "437th Airlift Wing",
    "Progress M-01M",
    "Satellite television",
    "UNESCO Intangible Cultural Heritage Lists",
    "Food contact materials",
    "Food contaminant",
    "Geographically Indicated Food",
    "Taste",
    "Serving size",
    "Guideline Daily Amount",
    "Platter",
    "Rolling pin",
    "Flattop grill",
    "Dish structure",
    "Food model",
    "Federal Ministry of Agriculture, Food and Regional Identity",
    "Etar Architectural-Ethnographic Complex",
    
    # === Root Concepts ===
    "Cuisine",
    "Food",
    "Dish",
    "Dishes",
    "Foods",

    # === Existing Root Concepts (deduplicated) ===
    "Culture",
    "Speak",
    "People",
    "School",
    "Diamond",
    "Airline",
    "Book",
    "Famine",
    "famine",
    "File",
    "virus",
    "fever",
    "Template",
    "How",
    "Portal",
    "Index",
    "List",
    "Team",
    "Operation",
    "Outline",
    "History",
    "Comparison",
    "Diet",
    "Vegetarianism",
    "Islam",

    # === Places ===
    "Thulhaadhoo",
    "Padang Panjang",
    "West Tampa",
    "Bagansiapiapi",
    "Padang Matsirat",
    "Wichian Buri district",
    "Brickfields",
    "Seremban District",
    "Toft",
    "Wilstead",
    "Buchkirchen",
    "Dhërmi",
    "Shelley",
    "El Quisco",
    "Huancarqui District",
    "Majes District",
    "Bouza Department",
    "Dély Ibrahim",
    "Orahovac",
    "Nankin-machi",

    # === People ===
    "Sanjeev Kapoor",
    "Cheong Liew",
    "Vikas Khanna",
    "John Torode",
    "Cindy McCain",
    "Anwar Choudhury",
    "Manju Malhi",
    "Abdul Latif",
    "Joan Nathan",
    "George Mardikian",
    "Nelson Mandela",
    "Maggie Beer",
    "Fabio Lanzoni",
    "Tony Brent",
    "David Galenson",
    "Aleix Espargaró",
    "Daren Ganga",
    "Toshikatsu Matsuoka",
    "Gotabaya Rajapaksa",
    "Mahabir Pun",
    "Yu Hayami",
    "Hallgerður Gísladóttir",
    "Jean-Paul Bruneteau",
    "Vic Cherikoff",

    # === Companies / Brands ===
    "Wolf Blass",
    "Haigh's Chocolates",
    "Golden North",
    "Beerenberg Farm",
    "Sakae Sushi",
    "Long Beach Seafood Restaurant",
    "Jumbo Seafood",
    "Mitsuwa Marketplace",
    "Wendy's Milk Bar",
    "Bloom's restaurant",
    "Fogo de Chão",
    "Versailles",
    "Quay",
    "Domino's Pizza",
    "Adyar Ananda Bhavan",
    "Veeraswamy",
    "Cibo Espresso",
    "Kart's",
    "Yatir winery",
    "Recanati winery",
    "Elderton Wines",
    "Pewsey Vale",
    "Torbreck",
    "Seppeltsfield",
    "Mountadam Vineyards",
    "Barkan Wine Cellars",
    "Schiller Vineyards",
    "Yalumba",
    "Golden Krust",
    "Trend Drinks",
    "Woodroofe",
    "Farmers Union",
    "Bee Cheng Hiang",
    "Prigat",
    "Sizzler",
    "Koni Store",
    "Ching's Secret",
    "Aashirvaad",

    # === Abstract Concepts ===
    "Americanization",
    "Arab Agricultural Revolution",
    "Assyrian culture",
    "Culinary tourism",
    "Food politics",
    "Food prohibitions",
    "Food waste",
    "Intensive animal farming",
    "Prophetic medicine",
    "Homelessness",

    # === Media / Shows ===
    "A Cook's Tour",
    "Anna & Kristina's Grocery Bag",
    "TV or Not TV",
    "Asadora",
    "The Secret of the Grain",
    "Upin & Ipin",
    "Chowder",
    "Tikka to Ride",
    "Sukiyaki Western Django",
    "Fantozzi",
    "Masala film",
    "Fan Pan Tae",
    "The Amazing Race 18",
    "Great British Railway Journeys",
    "The Rippling Blossom",

    # === Miscellaneous ===
    "BP-5 Compact Food",
    "GARIOA",
    "Feldgendarmerie",
    "437th Airlift Wing",
    "Progress M-01M",
    "Satellite television",
    "UNESCO Intangible Cultural Heritage Lists",
    "Food contact materials",
    "Food contaminant",
    "Geographically Indicated Food",
    "Taste",
    "Serving size",
    "Guideline Daily Amount",
    "Platter",
    "Rolling pin",
    "Flattop grill",
    "Dish structure",
    "Food model",
    "Federal Ministry of Agriculture, Food and Regional Identity",
    "Etar Architectural-Ethnographic Complex",

    # === New Terms from Dataset (Deduplicated by Root) ===
    "Anime",
    "Almond",
    "Alabaster",
    "Agar",
    "Book of Numbers",
    "Galjoen",
    "Constantin Brâncuși",
    "Curry",
    "Camel",
    "Couscous",
    "Dessert",
    "Dairy product",
    "Easter egg",
    "Evangelicalism",
    "French fries",
    "Green",
    "Humvee",
    "Papua (province)",
    "Jakarta",
    "Kashrut",
    "Kathmandu",
    "Kosovo",
    "London",
    "Mentha",
    "Maribor",
    "Malt",
    "Miso",
    "Nori",
    "Olive",
    "Parsley",
    "Potato",
    "Pasta",
    "Piper (plant)",
    "Riga",
    "Ramadan",
    "Seafood",
    "Telstra",
    "Worcestershire sauce",
    "Budapest",
    "Heart",
    "Drought",
    "Hippopotamus",
    "Ramen",
    "Nutmeg",
    "Banana",
    "Gelimer",
    "Shallot",
    "Queens",
    "Eggplant",
    "Hamburger",
    "Fish and chips",
    "Tuna",
    "7-Eleven",
    "Kolkata",
    "Chinese Americans",
    "Famine",
    "Pueblo peoples",
    "Gruyère cheese",
    "Stingray",
    "Tonkatsu",
    "Fast-food restaurant",
    "Shellfish",
    "Zagreb",
    "Flour",
    "Mango",
    "Obesity",
    "Asmara",
    "Chickpea",
    "Tapioca",
    "Palm oil",
    "Buryats",
    "Papaya",
    "Serbs",
    "Black cardamom",
    "Pygmy hippopotamus",
    "Sauce",
    "Soy sauce",
    "Monosodium glutamate",
    "Soybean",
    "Edamame",
    "Cashew",
    "Formaldehyde",
    "Tamale",
    "Galangal",
    "Sea urchin",
    "Lamington",
    "Ketchup",
    "Chop suey",
    "Breakfast",
    "Ceviche",
    "Orange (colour)",
    "Corned beef",
    "Kidney bean",
    "Cusco",
    "Poutine",
    "Pomegranate",
    "Doughnut",
    "Porridge",
    "Pinto bean",
    "Botifarra",
    "Glendale, California",
    "Edam cheese",
    "Tostada (tortilla)",
    "Colocasia",
    "London Borough of Tower Hamlets",
    "Recipe",
    "Dim sum",
    "Hors d'oeuvre",
    "Swain Reefs National Park",
    "Washington, D.C.",
    "Novi Sad",
    "Rosendale (CDP), New York",
    "Amberjack",
    "Salsa criolla",
    "Ennichi",
    "Nabemono",
    "Miso soup",
    "Onigiri",
    "Hiyayakko",
    "Tempura",
    "Okonomiyaki",
    "Soba",
    "Uirō",
    "Blubber",
    "Eid al-Fitr",
    "Udon",
    "Christmas Eve",
    "Hangzhou",
    "Donburi",
    "Arctium",
    "Perak",
    "Radish",
    "Juglans",
    "Boesenbergia rotunda",
    "Dashi",
    "Kamaboko",
    "Caraway",
    "Kansai region",
    "Peter Lehmann (winemaker)",
    "Barossa Valley",
    "Ponzu",
    "Tripe",
    "Chiba Prefecture",
    "Teppanyaki",
    "Takoyaki",
    "Niboshi",
    "Daikon",
    "Retail",
    "Song thrush",
    "Freeganism",
    "Illicium verum",
    "Chutney",
    "Edible mushroom",
    "International Security Assistance Force",
    "Allspice",
    "Kaffir lime",
    "Canning",
    "Satay",
    "Eurasian nuthatch",
    "Scotch bonnet",
    "Carleton University",
    "Glutinous rice",
    "Pancake",
    "Ghee",
    "Thick-billed raven",
    "Surabaya",
    "Borscht",
    "Akashiyaki",
    "Ian Anderson",
    "Milkfish",
    "Grocery store",
    "Coconut oil",
    "Asha Bhosle",
    "Erich Ludendorff",
    "String cheese",
    "Lime (fruit)",
    "Assyrian people",
    "Flushing, Queens",
    "Blintz",
    "Yum cha",
    "Seitan",
    "Urnfield culture",
    "Vranje",
    "Sprouting",
    "Brisket",
    "Tahini",
    "Fenugreek",
    "Hazelnut",
    "Tempeh",
    "Roe",
    "Sukiyaki",
    "Mantis shrimp",
    "Gefilte fish",
    "Stockport",
    "Scallop",
    "Piranha",
    "Croque monsieur",
    "Annatto",
    "Mangaluru",
    "Western Cape",
    "Katsuobushi",
    "Rock ptarmigan",
    "Kaga, Ishikawa",
    "Mobara",
    "Kameoka, Kyoto",
    "Chorizo",
    "Offal",
    "Ajwain",
    "Jambalaya",
    "Zabul Province",
    "Beetroot",
    "Ackee",
    "Baked Lamb and Yogurt",
    "Donation",
    "Citron",
    "Fërgesë of Tirana with Peppers",
    "Fërgesë of Tirana with Veal",
    "Caipirinha",
    "Prunus mume",
    "Meatloaf",
    "Manchurian",
    "Stuffing",
    "Nattō",
    "Rest area",
    "Helix (gastropod)",
    "Momordica charantia",
    "Kebab",
    "São Paulo",
    "Nasi lemak",
    "Faisalabad",
    "Blue cod",
    "Brick Lane",
    "Turrón",
    "Kedgeree",
    "Red-whiskered bulbul",
    "Laksa",
    "Black-eyed pea",
    "Pierogi",
    "Jim McGovern (American politician)",
    "Chrisp Street Market",
    "Black francolin",
    "Semolina"
]


with open(file="./csv/links.csv", mode="r", encoding="utf-8") as mother_file, open(file=CSV_TARGET_FILE, mode="w", encoding="utf-8") as child_file:
    read_links = csv.reader(mother_file)
    write = csv.writer(child_file)

    for row in read_links:
        if any(item in row[1] for item in FOOD_ELEMENTS) and any(item in row[1] for item in COUNTRY_ELEMENTS) and not any(item in row[0] for item in FOOD_ELEMENTS) and not any(item in row[0] for item in COUNTRY_ELEMENTS) and not any(item in row[0] for item in BANNED_WORDS) and not any(item in row[1] for item in BANNED_WORDS):
            print(row)
            write.writerow(row)
print("Done!")